site_name: pyquack
site_description: Simple Python sync/async duckduckgo wrapper.
site_author: Anand Krishna
site_url: https://anand2312.tech/pyquack

theme:
  name: material
  palette:
    - scheme: slate
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: default
      primary: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

repo_name: anand2312/pyquack
repo_url: https://github.com/anand2312/pyquack
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - API Reference: api_reference.md
  - Models: models.md

plugins:
- search
- mkdocstrings

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: "#"
  - pymdownx.highlight
  - pymdownx.superfences
